name: 'Provision VM'
description: 'Initializes, validates and builds a VM using Packer with the parameterized template'
inputs:
  input_image:
    description: 'URL or path to the input base image (cloud image or existing QCOW2)'
    required: true
  output_directory:
    description: 'Directory where the build output will be stored'
    required: true
  output_name:
    description: 'Name of the output VM file'
    required: true
  input_provision_script:
    description: 'Path to the provisioning script to run'
    required: true
  build_name:
    description: 'Descriptive name for this build (displayed in Packer logs and build metadata, does not affect output files)'
    required: true
  disk_compression:
    description: 'Enable qcow2 internal compression during Packer compaction (may slow builds)'
    required: false
    default: 'false'
  username:
    description: 'Username for the VM user account (used for SSH access during build and for local login on the built VM)'
    required: false
    default: 'packer'
  password:
    description: 'Password for the user (use plain text or a hash from mkpasswd/openssl, e.g., mkpasswd -m sha-512)'
    required: false
    default: ''
  hostname:
    description: 'Hostname for the VM'
    required: false
    default: 'vm-host'
  ssh_public_key:
    description: 'SSH public key for authentication'
    required: false
    default: ''
  ssh_private_key:
    description: 'SSH private key content for Packer to connect (will be written to a temporary file)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Check if Packer is already installed
      id: check-packer
      shell: bash
      run: |
        if command -v packer &> /dev/null; then
          echo "installed=true" >> $GITHUB_OUTPUT
          echo "Packer is already installed ($(packer version))"
        else
          echo "installed=false" >> $GITHUB_OUTPUT
          echo "Packer is not installed"
        fi

    - name: Setup Packer
      if: steps.check-packer.outputs.installed != 'true'
      uses: hashicorp/setup-packer@v3.1.0

    - name: Check and install QEMU dependencies
      shell: bash
      run: |
        PACKAGES=()
        command -v qemu-system-x86_64 &> /dev/null || PACKAGES+=("qemu-system-x86")
        command -v xorriso &> /dev/null || PACKAGES+=("xorriso")
        if [ ${#PACKAGES[@]} -gt 0 ]; then
          echo "Installing missing dependencies: ${PACKAGES[*]}"
          sudo apt-get update -qq
          sudo apt-get install -y -qq "${PACKAGES[@]}"
        else
          echo "All dependencies already installed"
        fi

    - name: Prepare SSH private key
      shell: bash
      run: |
        if [ -n "${{ inputs.ssh_private_key }}" ]; then
          mkdir -p /tmp/packer-ssh-keys
          chmod 700 /tmp/packer-ssh-keys
          cat > /tmp/packer-ssh-keys/packer_key << 'EOF'
        ${{ inputs.ssh_private_key }}
        EOF
          chmod 600 /tmp/packer-ssh-keys/packer_key
          echo "SSH_PRIVATE_KEY_FILE=/tmp/packer-ssh-keys/packer_key" >> $GITHUB_ENV
        else
          echo "SSH_PRIVATE_KEY_FILE=Packer/keys/packer_ed25519" >> $GITHUB_ENV
        fi

    - name: Initialize Packer template
      shell: bash
      run: packer init ${{ github.action_path }}/../template.pkr.hcl

    - name: Validate Packer template
      shell: bash
      run: |
        packer validate \
          -var "input_image=${{ inputs.input_image }}" \
          -var "output_directory=${{ inputs.output_directory }}" \
          -var "output_name=${{ inputs.output_name }}" \
          -var "input_provision_script=${{ inputs.input_provision_script }}" \
          -var "build_name=${{ inputs.build_name }}" \
          -var "disk_compression=${{ inputs.disk_compression }}" \
          -var "username=${{ inputs.username }}" \
          -var "password=${{ inputs.password }}" \
          -var "hostname=${{ inputs.hostname }}" \
          -var "ssh_public_key=${{ inputs.ssh_public_key }}" \
          -var "ssh_private_key_file=${SSH_PRIVATE_KEY_FILE}" \
          ${{ github.action_path }}/../template.pkr.hcl

    - name: Build VM with Packer
      shell: bash
      run: |
        packer build \
          -var "input_image=${{ inputs.input_image }}" \
          -var "output_directory=${{ inputs.output_directory }}" \
          -var "output_name=${{ inputs.output_name }}" \
          -var "input_provision_script=${{ inputs.input_provision_script }}" \
          -var "build_name=${{ inputs.build_name }}" \
          -var "disk_compression=${{ inputs.disk_compression }}" \
          -var "username=${{ inputs.username }}" \
          -var "password=${{ inputs.password }}" \
          -var "hostname=${{ inputs.hostname }}" \
          -var "ssh_public_key=${{ inputs.ssh_public_key }}" \
          -var "ssh_private_key_file=${SSH_PRIVATE_KEY_FILE}" \
          ${{ github.action_path }}/../template.pkr.hcl

    - name: Cleanup SSH private key
      if: always()
      shell: bash
      run: |
        rm -f /tmp/packer-ssh-keys/packer_key
        rmdir --ignore-fail-on-non-empty /tmp/packer-ssh-keys 2>/dev/null || true