name: 'Test Ubuntu Desktop VM'
description: 'Tests building an Ubuntu Desktop VM using the provision-vm action'

runs:
  using: 'composite'
  steps:
    - name: Generate SSH key pair
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t ed25519 -f ~/.ssh/packer_key -N ""
        echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/packer_key.pub)" >> $GITHUB_ENV
        echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
        cat ~/.ssh/packer_key >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Provision Ubuntu Desktop VM
      uses: ./provision-vm
      with:
        input_image: 'https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img'
        output_directory: './output'
        output_name: 'ubuntu-desktop-test.qcow2'
        build_name: 'ubuntu-desktop-test-build'
        inline_provision_commands: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies lightdm
          sudo systemctl set-default graphical.target
          echo "This Ubuntu Desktop VM was provisioned by Packer on $(date)" | sudo tee /home/ubuntu/provisioned_by_packer
          echo "Desktop environment installation complete!"
        username: 'ubuntu'
        hostname: 'ubuntu-desktop-test'
        ssh_public_key: ${{ env.SSH_PUBLIC_KEY }}
        ssh_private_key: ${{ env.SSH_PRIVATE_KEY }}
        user_groups: 'sudo'
        cloud_init_packages: 'sudo'
        shutdown_command: 'sudo shutdown -P now'

    - name: Check VM size
      shell: bash
      run: |
        ls -lh ./output/ubuntu-desktop-test.qcow2
        size=$(du -h ./output/ubuntu-desktop-test.qcow2 | cut -f1)
        echo "VM size: $size"

    - name: Upload VM artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-desktop-test-vm
        path: ./output/ubuntu-desktop-test.qcow2
